# Project Information
site_name: icopy.site
site_description: 开源文档中文镜像
site_author: chenjiajia
site_url: https://icopy-site.github.io

# Repository
repo_name: 'icopy-site/icopy-site.github.io'
repo_url: 'https://github.com/icopy-site/icopy-site.github.io'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2019'

# Contents
nav:
  - 文档:
    - 构建镜像站: index.md
    - 编程语言: document/language.md
    - 框架: document/framework.md
    - 数据库: document/database.md
    - 印记中文: https://docschina.org/
  - AWESOME:
    - 资源列表: awesome/readme.md
    - 中文: https://asmcn.icopy.site/
    - 英文: https://asmen.icopy.site/


# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  feature:
    tabs: true
# Customization
extra:
  search:
    language: 'jp'
  copyright: 'CC BY-NC-SA 4.0'

extra_javascript:
  - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
  - '_static/js/extra.js'
  - 'https://cdn.staticfile.org/jquery/3.3.1/jquery.min.js'
  - 'https://cdn.staticfile.org/github-repo-widget/e23d85ab8f/jquery.githubRepoWidget.min.js'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'http://tajs.qq.com/stats?sId=65686228'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
